ALTER TABLE `user`
ADD COLUMN `dateOfBirth` DATETIME(3) NULL,
ADD COLUMN `birthTime` VARCHAR(191) NULL,
ADD COLUMN `placeOfBirth` VARCHAR(191) NULL,
ADD COLUMN `latitudeDeg` INTEGER NULL,
ADD COLUMN `latitudeMin` INTEGER NULL,
ADD COLUMN `latitudeDir` VARCHAR(1) NULL,
ADD COLUMN `longitudeDeg` INTEGER NULL,
ADD COLUMN `longitudeMin` INTEGER NULL,
ADD COLUMN `longitudeDir` VARCHAR(1) NULL,
ADD COLUMN `timezone` DOUBLE NULL,
ADD COLUMN `kpHoraryNumber` INTEGER NULL;